<?php

require_once '../config/database.php';
requireAdmin();

// Get filter parameters
$filter_date_from = isset($_GET['date_from']) ? clean($_GET['date_from']) : date('Y-m-01');
$filter_date_to = isset($_GET['date_to']) ? clean($_GET['date_to']) : date('Y-m-d');
$filter_product = isset($_GET['product']) ? intval($_GET['product']) : '';

// Build query with filters
$where_clauses = ["c.purchase_date BETWEEN '$filter_date_from' AND '$filter_date_to'"];
if ($filter_product) {
    $where_clauses[] = "c.product_id = $filter_product";
}
$where_sql = implode(' AND ', $where_clauses);

// Get COGS records
$cogs_query = "SELECT c.*, p.product_name, pv.variant_type, pv.variant_value, u.full_name as created_by_name
               FROM cost_of_goods_sold c
               JOIN products p ON c.product_id = p.product_id
               LEFT JOIN product_variants pv ON c.variant_id = pv.variant_id
               LEFT JOIN users u ON c.created_by = u.user_id
               WHERE $where_sql
               ORDER BY c.purchase_date DESC, c.created_at DESC";
$cogs_records = mysqli_query($conn, $cogs_query);

// Calculate totals
$totals_query = "SELECT 
                 SUM(total_cost) as total_cogs,
                 SUM(quantity) as total_quantity,
                 COUNT(*) as total_entries,
                 AVG(unit_cost) as avg_unit_cost
                 FROM cost_of_goods_sold c
                 WHERE $where_sql";
$totals_result = mysqli_query($conn, $totals_query);
$totals = mysqli_fetch_assoc($totals_result);

// Set headers for CSV download
$filename = "COGS_Report_" . $filter_date_from . "_to_" . $filter_date_to . ".csv";
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

// Create output stream
$output = fopen('php://output', 'w');

// Add BOM for Excel UTF-8 support
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// Write report header
fputcsv($output, ['UniNeeds - Cost of Goods Sold Report']);
fputcsv($output, ['Report Period:', $filter_date_from . ' to ' . $filter_date_to]);
fputcsv($output, ['Generated:', date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated By:', $_SESSION['full_name']]);
fputcsv($output, []);

// Write summary
fputcsv($output, ['SUMMARY']);
fputcsv($output, ['Total COGS:', 'PHP ' . number_format($totals['total_cogs'], 2)]);
fputcsv($output, ['Total Units Purchased:', number_format($totals['total_quantity'])]);
fputcsv($output, ['Total Entries:', $totals['total_entries']]);
fputcsv($output, ['Average Unit Cost:', 'PHP ' . number_format($totals['avg_unit_cost'], 2)]);
fputcsv($output, []);

// Write column headers
fputcsv($output, [
    'Date',
    'Product Name',
    'Variant',
    'Quantity',
    'Unit Cost (PHP)',
    'Total Cost (PHP)',
    'Supplier',
    'Invoice Number',
    'Notes',
    'Receipt Attached',
    'Created By',
    'Created At'
]);

// Write data rows
while ($row = mysqli_fetch_assoc($cogs_records)) {
    $variant = '';
    if ($row['variant_type']) {
        $variant = $row['variant_type'] . ': ' . $row['variant_value'];
    }
    
    fputcsv($output, [
        date('Y-m-d', strtotime($row['purchase_date'])),
        $row['product_name'],
        $variant,
        $row['quantity'],
        number_format($row['unit_cost'], 2),
        number_format($row['total_cost'], 2),
        $row['supplier'],
        $row['invoice_number'],
        $row['notes'],
        $row['receipt_path'] ? 'Yes' : 'No',
        $row['created_by_name'],
        date('Y-m-d H:i:s', strtotime($row['created_at']))
    ]);
}

// Write footer
fputcsv($output, []);
fputcsv($output, ['End of Report']);

fclose($output);
exit();
?>