<?php

require_once '../config/database.php';
requireAdmin();

// Get filter parameters
$filter_date_from = isset($_GET['date_from']) ? clean($_GET['date_from']) : date('Y-m-01');
$filter_date_to = isset($_GET['date_to']) ? clean($_GET['date_to']) : date('Y-m-d');
$filter_type = isset($_GET['type']) ? clean($_GET['type']) : '';

// Build query with filters
$where_clauses = ["expense_date BETWEEN '$filter_date_from' AND '$filter_date_to'"];
if ($filter_type) {
    $where_clauses[] = "expense_type = '" . mysqli_real_escape_string($conn, $filter_type) . "'";
}
$where_sql = implode(' AND ', $where_clauses);

// Get expenses
$expenses_query = "SELECT e.*, u.full_name as created_by_name
                   FROM expenses e
                   LEFT JOIN users u ON e.created_by = u.user_id
                   WHERE $where_sql
                   ORDER BY e.expense_date DESC, e.created_at DESC";
$expenses = mysqli_query($conn, $expenses_query);

// Calculate totals by type
$totals_query = "SELECT 
                 expense_type,
                 SUM(amount) as type_total,
                 COUNT(*) as type_count
                 FROM expenses
                 WHERE $where_sql
                 GROUP BY expense_type";
$totals_result = mysqli_query($conn, $totals_query);

$type_totals = [];
$grand_total = 0;
$total_count = 0;

while ($row = mysqli_fetch_assoc($totals_result)) {
    $type_totals[$row['expense_type']] = [
        'total' => $row['type_total'],
        'count' => $row['type_count']
    ];
    $grand_total += $row['type_total'];
    $total_count += $row['type_count'];
}

// Set headers for CSV download
$filename = "Expenses_Report_" . $filter_date_from . "_to_" . $filter_date_to . ".csv";
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');

// Create output stream
$output = fopen('php://output', 'w');

// Add BOM for Excel UTF-8 support
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

// Write report header
fputcsv($output, ['UniNeeds - Expenses Report']);
fputcsv($output, ['Report Period:', $filter_date_from . ' to ' . $filter_date_to]);
fputcsv($output, ['Generated:', date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated By:', $_SESSION['full_name']]);
fputcsv($output, []);

// Write summary
fputcsv($output, ['SUMMARY']);
fputcsv($output, ['Total Expenses:', 'PHP ' . number_format($grand_total, 2)]);
fputcsv($output, ['Total Transactions:', $total_count]);
fputcsv($output, []);

// Write breakdown by type
fputcsv($output, ['BREAKDOWN BY TYPE']);
fputcsv($output, ['Expense Type', 'Count', 'Total Amount']);

// Define expense type labels
$expense_type_labels = [
    'transportation' => 'Transportation',
    'utilities' => 'Utilities',
    'rent' => 'Rent',
    'supplies' => 'Office Supplies',
    'maintenance' => 'Maintenance & Repairs',
    'marketing' => 'Marketing & Advertising',
    'communication' => 'Communication',
    'insurance' => 'Insurance',
    'professional_fees' => 'Professional Fees',
    'miscellaneous' => 'Miscellaneous'
];

foreach ($type_totals as $type => $data) {
    $type_label = isset($expense_type_labels[$type]) ? $expense_type_labels[$type] : ucfirst($type);
    fputcsv($output, [
        $type_label,
        $data['count'],
        'PHP ' . number_format($data['total'], 2)
    ]);
}

fputcsv($output, []);
fputcsv($output, []);

// Write detailed transactions
fputcsv($output, ['DETAILED TRANSACTIONS']);
fputcsv($output, ['Date', 'Type', 'Description', 'Amount', 'Payment Method', 'Vendor/Supplier', 'Receipt/Reference', 'Created By', 'Notes']);

// Reset pointer for expenses result
mysqli_data_seek($expenses, 0);

while ($expense = mysqli_fetch_assoc($expenses)) {
    $type_label = isset($expense_type_labels[$expense['expense_type']]) 
        ? $expense_type_labels[$expense['expense_type']] 
        : ucfirst($expense['expense_type']);
    
    fputcsv($output, [
        date('M d, Y', strtotime($expense['expense_date'])),
        $type_label,
        $expense['description'] ?? '',
        'PHP ' . number_format($expense['amount'], 2),
        ucfirst($expense['payment_method'] ?? 'N/A'),
        $expense['vendor_supplier'] ?? '',
        $expense['receipt_reference'] ?? '',
        $expense['created_by_name'] ?? 'N/A',
        $expense['notes'] ?? ''
    ]);
}

// Close output stream
fclose($output);

// Exit to prevent any additional output
exit();
?>